baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Xinyu Wu's blog"
theme = "maupassant"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4